name: CI DevSecOps

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install dependencies
      run: composer install

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

  sast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SonarQube scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .

  dast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run OWASP ZAP
      uses: zaproxy/action-baseline@v0.6.0
      with:
        target: 'http://localhost'
